export enum TaskStatus {
    OPEN = 'OPEN',
    PENDING_OFFER = 'PENDING_OFFER',
    ASSIGNED = 'ASSIGNED',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    UNCONCLUDED = 'UNCONCLUDED',
}
